CREATE TABLE card(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	lote VARCHAR(3)  NULL,
	numero VARCHAR(40) NOT NULL
)ENGINE=innoDB DEFAULT CHARSET=utf8;

CREATE TABLE usuario(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	login VARCHAR(20) NOT NULL,
	senha VARCHAR(100) NOT NULL
)ENGINE=innoDB DEFAULT CHARSET=utf8;



